export const shopTypes = {
    FETCH_SHOPS: 'FETCH_SHOPS',
    FETCH_SHOPS_SUCCESS: 'FETCH_SHOPS_SUCCESS',
    FETCH_SHOPS_ERROR: 'FETCH_SHOPS_ERROR',
    CHANGE_SHOP: 'CHANGE_SHOP'
}

export const cartTypes = {
    CHANGE_CART: 'CHANGE_CART'
}

export const historyTypes = {
    FETCH_HISTORY: 'FETCH_HISTORY',
    FETCH_HISTORY_SUCCESS: 'FETCH_HISTORY_SUCCESS',
    FETCH_HISTORY_ERROR: 'FETCH_HISTORY_ERROR',
    CHANGE_HISTORY_DATA: 'CHANGE_HISTORY_DATA'
}