export const shopTypes = {
    FETCH_SHOPS: 'FETCH_SHOPS',
    FETCH_SHOPS_SUCCESS: 'FETCH_SHOPS_SUCCESS',
    FETCH_SHOPS_ERROR: 'FETCH_SHOPS_ERROR',
    CHANGE_SHOP: 'CHANGE_SHOP'
}

export const cartTypes = {
    CHANGE_CART: 'CHANGE_CART'
}